version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      WEBSOCKET_ENABLED: ${WEBSOCKET_ENABLED}
      LOGIN_RATELIMIT_MAX_BURST: ${LOGIN_RATELIMIT_MAX_BURST}
      LOGIN_RATELIMIT_SECONDS: ${LOGIN_RATELIMIT_SECONDS}
      ADMIN_RATELIMIT_MAX_BURST: ${ADMIN_RATELIMIT_MAX_BURST}
      ADMIN_RATELIMIT_SECONDS: ${ADMIN_RATELIMIT_SECONDS}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      SENDS_ALLOWED: ${SENDS_ALLOWED}
      EMERGENCY_ACCESS_ALLOWED: ${EMERGENCY_ACCESS_ALLOWED}
      WEB_VAULT_ENABLED: ${WEB_VAULT_ENABLED}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
      SIGNUPS_VERIFY: ${SIGNUPS_VERIFY}
      SIGNUPS_VERIFY_RESEND_TIME: ${SIGNUPS_VERIFY_RESEND_TIME}
      SIGNUPS_VERIFY_RESEND_LIMIT: ${SIGNUPS_VERIFY_RESEND_LIMIT}
      SIGNUPS_DOMAINS_WHITELIST: ${SIGNUPS_DOMAINS_WHITELIST}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME}
      SMTP_SECURITY: ${SMTP_SECURITY}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_AUTH_MECHANISM: ${SMTP_AUTH_MECHANISM}

    volumes:
      - ./vw-data:/data

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
    environment:
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL} 
      LOG_FILE: "/data/access.log"

